# Site settings
title:  zsp的个人博客 
subtitle: 道阻且长，行则将至
name: zsp的个人博客 
email: 592366758@qq.com
description: 本站是zsp的个人博客的技术分享博客。
keywords: zsp的个人博客,Spring,Spring Boot,Spring Cloud,Jvm,Docker,生活故事,架构,Java
encoding: "utf-8"
favicon: favicon.ico 

repository: zsp419/zspblog.github.io
github_url: https://github.com/zsp419
url: https://www.zsp419.top/
enforce_ssl: zsp419.top

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'
